apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  env: dev
resources:
- ../../base
patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 100m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 128Mi
- target:
    kind: HorizontalPodAutoscaler
    name: .*
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
- target:
    kind: ConfigMap
    name: .*
  patch: |-
    - op: replace
      path: /data/LOG_LEVEL
      value: debug
    - op: replace
      path: /data/ENVIRONMENT
      value: dev
    - op: replace
      path: /data/POSTGRES_DB
      value: learnflow_dev
