#!/bin/bash
# Enterprise PostgreSQL deployment script

# Parse command line arguments
ENVIRONMENT="development"
HA_ENABLED=false
BACKUP_ENABLED=false
SSL_ENABLED=false
MONITORING_ENABLED=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --ha-enabled)
            HA_ENABLED=true
            shift
            ;;
        --backup-enabled)
            BACKUP_ENABLED=true
            shift
            ;;
        --ssl)
            SSL_ENABLED=true
            shift
            ;;
        --monitoring)
            MONITORING_ENABLED=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Set up enterprise configuration
CLUSTER_NAME="postgresql"
NAMESPACE="postgres"
REPLICAS=1
STORAGE_CLASS="standard"

# Adjust replicas for HA
if [ "$HA_ENABLED" = true ]; then
    REPLICAS=3
    STORAGE_CLASS="premium-rwo"
    echo "High Availability enabled: setting replicas to $REPLICAS and storage class to $STORAGE_CLASS"
fi

# Create namespace if it doesn't exist
echo "Creating namespace $NAMESPACE if it doesn't exist..."
kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
echo "✓ Namespace '$NAMESPACE' ensured."

# Add enterprise labels
kubectl label namespace $NAMESPACE \
    environment=$ENVIRONMENT \
    managed-by=opencode-skills \
    db-type=postgresql \
    --overwrite

# Deploy Helm chart with enterprise options
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update

# Build Helm command with enterprise flags
HELM_CMD="helm upgrade --install $CLUSTER_NAME bitnami/postgresql --namespace $NAMESPACE"
HELM_CMD="$HELM_CMD --set replicaCount=$REPLICAS"
HELM_CMD="$HELM_CMD --set primary.persistence.enabled=true"
HELM_CMD="$HELM_CMD --set primary.persistence.storageClass=$STORAGE_CLASS"
HELM_CMD="$HELM_CMD --set primary.persistence.size=10Gi"
HELM_CMD="$HELM_CMD --set auth.postgresPassword='postgres'"
HELM_CMD="$HELM_CMD --set auth.username='postgres'"
HELM_CMD="$HELM_CMD --set auth.database='learnflow'"
HELM_CMD="$HELM_CMD --set service.type=ClusterIP"

if [ "$SSL_ENABLED" = true ]; then
    HELM_CMD="$HELM_CMD --set tls.enabled=true"
    HELM_CMD="$HELM_CMD --set tls.autoGenerated=true"
    echo "SSL/TLS encryption enabled for PostgreSQL."
fi

if [ "$HA_ENABLED" = true ]; then
    HELM_CMD="$HELM_CMD --set architecture.mode=replication"
    HELM_CMD="$HELM_CMD --set primary.service.type=LoadBalancer" # Expose primary for external access
    HELM_CMD="$HELM_CMD --set readReplicas.persistence.enabled=true"
    HELM_CMD="$HELM_CMD --set readReplicas.persistence.storageClass=$STORAGE_CLASS"
    HELM_CMD="$HELM_CMD --set readReplicas.replicaCount=$((REPLICAS - 1))"
    echo "PostgreSQL High Availability configured with replication."
fi

if [ "$BACKUP_ENABLED" = true ]; then
    # This is a placeholder for integrating a dedicated backup solution like Velero or pg_backup_tool
    echo "ℹ️ Backup integration enabled. A dedicated backup solution needs to be configured separately."
    echo "   Refer to REFERENCE.md for integrating Velero or other enterprise backup solutions."
fi

if [ "$MONITORING_ENABLED" = true ]; then
    HELM_CMD="$HELM_CMD --set metrics.enabled=true"
    HELM_CMD="$HELM_CMD --set metrics.serviceMonitor.enabled=true"
    HELM_CMD="$HELM_CMD --set metrics.serviceMonitor.namespace=$NAMESPACE"
    echo "PostgreSQL monitoring (Prometheus ServiceMonitor) enabled."
fi

echo "Deploying enterprise PostgreSQL cluster..."
eval $HELM_CMD

if [ $? -eq 0 ]; then
    echo "✓ Enterprise PostgreSQL cluster deployed successfully."
else
    echo "❌ PostgreSQL deployment failed."
    exit 1
fi

# Wait for deployment with timeout
echo "Waiting for PostgreSQL cluster to become ready..."
kubectl wait --namespace $NAMESPACE \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/name=postgresql \
    --timeout=600s

# Store deployment details for verification (optional, for later scripts)
echo "CLUSTER_NAME=$CLUSTER_NAME" > ../.postgresql-deployment-info
echo "NAMESPACE=$NAMESPACE" >> ../.postgresql-deployment-info
echo "ENVIRONMENT=$ENVIRONMENT" >> ../.postgresql-deployment-info
echo "HA_ENABLED=$HA_ENABLED" >> ../.postgresql-deployment-info
echo "BACKUP_ENABLED=$BACKUP_ENABLED" >> ../.postgresql-deployment-info
echo "SSL_ENABLED=$SSL_ENABLED" >> ../.postgresql-deployment-info
echo "MONITORING_ENABLED=$MONITORING_ENABLED" >> ../.postgresql-deployment-info

echo "✓ Enterprise PostgreSQL deployment complete."
